<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="ContactsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=159.148.144.30;User ID=PaskalaRitenisNewUser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Kontakti" Member="Kontakts">
    <Type Name="Kontakti">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NorisesVieta" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Adrese" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PapildusInfo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>