<?xml version="1.0" encoding="utf-8"?><Database Name="DU_IK_PaskalaRitenisNew" Class="OProgrammaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=159.148.144.30;Initial Catalog=DU_IK_PaskalaRitenisNew;User ID=PaskalaRitenisNewUser" SettingsObjectName="Repository.Properties.Settings" SettingsPropertyName="DU_IK_PaskalaRitenisNewConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OlimpProgramma" Member="OlimpProgrammas">
    <Type Name="OlimpProgramma">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Programma" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>